### ISSUE TITLE
[24] Bahnhöfe aus DB-Daten in OSM mappen

### ISSUE THREAD

**Issue by Goldkehle** [maximilianruesch/soro-s#18]
### Description

Um ein sinnvoll aufgeteiltes Verfahren zu gewährleisten, sollen hier alle Bahnhöfe, die in den DB-Daten vorliegen in OSM übertragen werden.

### Acceptance Criteria

Alle Bahnhöfe in den DB-Daten werden in der OSM-Ansicht als solche korrekt angezeigt.

### Meta

| **Field**              |    **Value**    |
|-----------------|:------------:|
| Story ID               |           24           |
| Story Points        |           4           |
| Implemented by | *Seen in history / assignment* |
| Finished in It #   |            -           |
| Total time           |            -           |
| Velocity              |            -           |

**Comment by maximilianruesch** [comment]
Irrelevant, da die DB Daten gar keine Bahnhöfe enthalten.
