### ISSUE TITLE
OSM Rail herunterladen und anzeigen

### ISSUE THREAD

**Issue by maximilianruesch** [maximilianruesch/soro-s#6]
### Description

Die OSM Daten sollten heruntergeladen und nach Rail gefiltert werden. Dadurch sollte es schon möglich sein, diese im Webclient anzuzeigen.

### Acceptance Criteria

OSM Rail Daten werden bei Server Startup geladen und sind über den Webclient selektierbar.

### Meta

| **Field**              |    **Value**    |
|-----------------|:------------:|
| Story ID               |           2          |
| Story Points        |           4           |
| Implemented by | *Seen in history / assignment* |
| Finished in It #   |            -           |
| Total time           |            -           |
| Velocity              |            -           |

**Comment by rydeom** [comment]
TEMPLATE PLS 💢
