### ISSUE TITLE
Strukturen der Kategorie "detail" haben im Dark Mode eine unpassende Farbe

### ISSUE THREAD

**Issue by ErikLille0** [maximilianruesch/soro-s#69]
### Description

Die Standartfarbe für Strukturen der Kategorie "detail" ist "#ccc" (Ein Grauton), wodurch diese im Darkmode unangenehm hervortreten

### Acceptance Criteria

Sowohl im Dark als auch im Light Mode sind die Strukturen der Kategorie "detail" sichtbar, allerdings nicht übermäßig auffällig

### Notes

![image](https://user-images.githubusercontent.com/117826826/220624223-f25f6924-1d6c-40d5-b4d3-b390904df9b0.png)

**Comment by maximilianruesch** [comment]
Nicht mehr relevant, da mit dem Mapping aus den Daten die meisten Detail-Strukturen nicht mehr enthalten sind und deshalb dieses Verhalten nicht mehr so zum Problem wird.
